version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: school_management_db
    ports:
      - "5999:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: school_management
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
